# Using the GCC Template for deploying kubespray
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    free -m && df -h && cat /etc/issue && cat /proc/cpuinfo && uname -a
    sudo apt-get update -y
    sudo apt-add-repository ppa:ansible/ansible && sudo apt-get install -y ansible git
    which ansible && which git && ansible --version
